<?php
$HOTELS = [
  ['id'=>1,'name'=>'The Alana Surabaya','location'=>'Surabaya Pusat','loc_full'=>'Jl. Mayjend Yono Suwoyo, Surabaya Pusat','rating'=>4.7,'reviews'=>1284,'stars'=>5,'base_price'=>650000,'tax_rate'=>0.11,'service_fee'=>25000,'grad'=>'linear-gradient(135deg,#667eea,#764ba2)','badge'=>'Best Value','amenities'=>['WiFi Gratis','Kolam Renang','Gym','Sarapan','Parkir','AC','TV','Minibar'],'dist'=>'0.3 km pusat kota','cancel_policy'=>'Gratis batalkan hingga 24 jam sebelum check-in','desc'=>'Hotel bintang 5 di jantung Surabaya dengan fasilitas premium dan pemandangan kota.'],
  ['id'=>2,'name'=>'Luminor Hotel','location'=>'Surabaya Timur','loc_full'=>'Jl. Kepanjen, Surabaya Timur','rating'=>4.5,'reviews'=>876,'stars'=>4,'base_price'=>420000,'tax_rate'=>0.11,'service_fee'=>20000,'grad'=>'linear-gradient(135deg,#f093fb,#f5576c)','badge'=>'Popular','amenities'=>['WiFi Gratis','Sarapan','Parkir','AC','TV'],'dist'=>'1.2 km Pakuwon Mall','cancel_policy'=>'Gratis batalkan hingga 48 jam sebelum check-in','desc'=>'Hotel modern desain kontemporer, pilihan sempurna bisnis maupun liburan.'],
  ['id'=>3,'name'=>'Swiss-Belinn Surabaya','location'=>'Surabaya Barat','loc_full'=>'Jl. Indrapura, Surabaya Barat','rating'=>4.3,'reviews'=>532,'stars'=>3,'base_price'=>280000,'tax_rate'=>0.11,'service_fee'=>15000,'grad'=>'linear-gradient(135deg,#4facfe,#00f2fe)','badge'=>'Budget Pick','amenities'=>['WiFi Gratis','AC','Parkir','Minibar'],'dist'=>'0.8 km Bandara Juanda','cancel_policy'=>'Non-refundable — sudah termasuk diskon maksimal','desc'=>'Pilihan cerdas bagi pelancong hemat, lokasi strategis dekat bandara.'],
  ['id'=>4,'name'=>'JW Marriott Surabaya','location'=>'Surabaya Pusat','loc_full'=>'Jl. Embong Malang, Surabaya Pusat','rating'=>4.9,'reviews'=>2341,'stars'=>5,'base_price'=>1250000,'tax_rate'=>0.11,'service_fee'=>50000,'grad'=>'linear-gradient(135deg,#fa709a,#fee140)','badge'=>'Top Rated','amenities'=>['WiFi Gratis','Kolam Renang','Spa','Gym','Sarapan','Bar','Parkir','AC','TV','Minibar'],'dist'=>'0.1 km pusat kota','cancel_policy'=>'Gratis batalkan hingga 72 jam sebelum check-in','desc'=>'Pengalaman menginap tertinggi di Surabaya dengan layanan kelas dunia.'],
];
function rp($n){return 'Rp '.number_format($n,0,',','.');}
function fd($d){return date('d M Y',strtotime($d));}
function fds($d){return date('d M',strtotime($d));}
